from __future__ import annotations

import re

from stackscan.types import Technology

_OBFUSCATION_PATTERNS: tuple[str, ...] = (
    r"eval\s*\(",
    r"Function\s*\(",
    r"atob\s*\(",
    r"btoa\s*\(",
    r"String\.fromCharCode",
    r"\\x[0-9a-fA-F]{2}",
    r"\\u[0-9a-fA-F]{4}",
)

_AI_KEYWORDS: tuple[str, ...] = (
    "generated by",
    "generated with",
    "created by ai",
    "vibe coded",
    "vibe-coded",
    "vibecoded",
    "ai assistant",
    "openai",
    "chatgpt",
    "claude",
    "copilot",
    "github copilot",
    "v0.dev",
    "lovable",
    "bolt.new",
    "llm generated",
    "artificial intelligence",
)

_TAILWIND_PREFIXES: tuple[str, ...] = (
    "bg-",
    "text-",
    "p-",
    "px-",
    "py-",
    "m-",
    "mx-",
    "my-",
    "rounded-",
    "shadow-",
    "flex",
    "grid",
    "gap-",
    "justify-",
    "items-",
    "content-",
    "border-",
    "hover:",
    "focus:",
    "sm:",
    "md:",
    "lg:",
    "xl:",
    "2xl:",
    "container",
    "w-",
    "h-",
    "min-w-",
    "min-h-",
    "max-w-",
    "max-h-",
)

_SEMANTIC_SECTIONS: tuple[str, ...] = (
    "header",
    "footer",
    "hero",
    "main",
    "sidebar",
    "navigation",
    "nav",
    "content",
    "section",
    "features",
    "about",
    "contact",
    "testimonials",
    "pricing",
    "faq",
    "cta",
    "login",
    "register",
    "dashboard",
)

_HTML_COMMENT_RE = re.compile(r"<!--(.*?)-->", re.DOTALL)
_JS_CSS_COMMENT_RE = re.compile(r"/\*(.*?)\*/", re.DOTALL)
_JS_LINE_COMMENT_RE = re.compile(r"//(.*)$", re.MULTILINE)
_CLASS_RE = re.compile(r'class=["\']([^"\']+)["\']', re.IGNORECASE)
_SCRIPT_RE = re.compile(r"<script[^>]*>(.*?)</script>", re.DOTALL | re.IGNORECASE)
_STYLE_RE = re.compile(r"<style[^>]*>(.*?)</style>", re.DOTALL | re.IGNORECASE)
_IDENTIFIER_RE = re.compile(r"\b[a-zA-Z_$][a-zA-Z0-9_$]*\b")
_EMOJI_RE = re.compile(
    r"["
    r"\U0001F600-\U0001F64F"
    r"\U0001F300-\U0001F5FF"
    r"\U0001F680-\U0001F6FF"
    r"\U0001F1E0-\U0001F1FF"
    r"\U00002702-\U000027B0"
    r"\U000024C2-\U0001F251"
    r"]+"
)


def _extract_scripts(body: str) -> str:
    return " ".join(match.group(1) for match in _SCRIPT_RE.finditer(body))


def _count_emojis(body: str) -> int:
    return len(_EMOJI_RE.findall(body))


def _is_obfuscated(body: str) -> bool:
    """Return True when the page looks intentionally obfuscated/minified."""
    scripts = _extract_scripts(body)
    combined = body if len(scripts) < 500 else scripts

    for pattern in _OBFUSCATION_PATTERNS:
        if re.search(pattern, combined):
            return True

    identifiers = _IDENTIFIER_RE.findall(scripts)
    if len(identifiers) >= 50:
        single_letter = sum(1 for name in identifiers if len(name) == 1)
        if single_letter / len(identifiers) > 0.35:
            return True
        short_names = sum(1 for name in identifiers if len(name) <= 2)
        if short_names / len(identifiers) > 0.55:
            return True
    return False


def _count_comments(body: str) -> int:
    html = len(_HTML_COMMENT_RE.findall(body))
    css = len(_JS_CSS_COMMENT_RE.findall(body))
    js = len(_JS_LINE_COMMENT_RE.findall(body))
    return html + css + js


def _ai_keyword_hits(body: str) -> list[str]:
    lower = body.lower()
    hits: list[str] = []
    for keyword in _AI_KEYWORDS:
        if keyword in lower:
            hits.append(keyword)
    return hits


def _tailwind_score(body: str) -> int:
    classes = _CLASS_RE.findall(body)
    if not classes:
        return 0
    all_classes = " ".join(classes)
    hits = sum(1 for prefix in _TAILWIND_PREFIXES if prefix in all_classes)
    return min(hits * 2, 25)


def _semantic_comment_score(body: str) -> int:
    comments = _HTML_COMMENT_RE.findall(body)
    if not comments:
        return 0
    hits = 0
    for comment in comments:
        text = comment.strip().lower().strip(": -")
        if text in _SEMANTIC_SECTIONS or any(text.startswith(s) for s in _SEMANTIC_SECTIONS):
            hits += 1
    return min(hits * 10, 30)


def _ai_generator_score(body: str) -> int:
    lower = body.lower()
    generator_match = re.search(
        r'<meta[^>]+name=["\']generator["\'][^>]+content=["\']([^"\']+)["\']',
        lower,
        re.IGNORECASE,
    )
    if generator_match:
        generator = generator_match.group(1)
        ai_tools = ("chatgpt", "openai", "claude", "copilot", "v0", "lovable", "bolt", "vibe")
        if any(tool in generator for tool in ai_tools):
            return 40
    return 0


def detect_vibe_code(body: str) -> list[Technology]:
    """Heuristic detection of AI-generated / 'vibe-coded' frontend markup.

    Returns a Technology hit when the page looks like readable, commented markup
    produced by an LLM rather than hand-written or obfuscated production code.
    """
    if not body or len(body) < 200:
        return []
    if _is_obfuscated(body):
        return []

    score = 0
    evidence: list[str] = []

    comment_count = _count_comments(body)
    if comment_count:
        score += min(comment_count * 5, 25)
        evidence.append(f"{comment_count} comment(s)")

    ai_hits = _ai_keyword_hits(body)
    if ai_hits:
        score += 30
        evidence.append(f"AI keyword(s): {', '.join(ai_hits[:3])}")

    tailwind = _tailwind_score(body)
    if tailwind:
        score += tailwind
        evidence.append("utility-first CSS patterns")

    semantic = _semantic_comment_score(body)
    if semantic:
        score += semantic
        evidence.append("semantic section comments")

    generator = _ai_generator_score(body)
    if generator:
        score += generator
        evidence.append("generator meta mentions AI")

    emoji_count = _count_emojis(body)
    if emoji_count >= 3:
        score += min(15 + emoji_count * 3, 30)
        evidence.append(f"{emoji_count} emoji(s)")

    evidence.append("readable/non-obfuscated source")

    if score < 40:
        return []

    return [
        Technology(
            name="Vibe-coded",
            categories=("ai-generated",),
            evidence=tuple(evidence),
            confidence=min(score, 100),
        )
    ]
